### ISSUE TITLE
Integrating this work into another project

### ISSUE THREAD

**Issue by Prince781** [davidmhewitt/vala-language-server#2]
Hello from https://github.com/benwaffle/vala-language-server.

Some of this work is quite useful and, with your permission, we would like to integrate it into the project above. After your permission, the other issue is whether you can relicense this code as LPGL 2.1, which is what vala is licensed as.

Please let me know what you think.

**Comment by davidmhewitt** [comment]
Hello,

Nice to see someone still working on a language server implementation! Work on this one stalled when I discovered a large number of leaks in libvala that made this language server almost unusable due to the memory usage. I spent some time fixing a lot of those upstream in vala and then other priorities took over.

You'd be very welcome to take parts of this project and relicense it too if you wish. Though, be warned that the formatter part of my implementation (which I think is the part you're interested in?) is not perfect and had a habit of breaking the code it formats!

At the very least it strips some of the comments out (because the vala parser does not keep all of these). But in some edge cases, it can break parts of the code too.

If you'd prefer, I could start working on your implementation and bring some of this code across myself as it is something I'd like to start working on again.

**Comment by Prince781** [comment]
> Work on this one stalled when I discovered a large number of leaks in libvala

Yeah, we ran into this same problem, and addressed it (to a degree, still inadequately) [here](https://github.com/benwaffle/vala-language-server/blob/master/vala038_workarounds.vala). But since vala 0.38 we've benefited greatly from the upstream work in reducing memory usage. Thanks for that.

>If you'd prefer, I could start working on your implementation and bring some of this code across myself as it is something I'd like to start working on again.

Sure, this would be a good idea. The code is very hackish; sorry about that. But we'd be glad to have another person (especially with probably a bit more time on their hands than we have) taking a look at these problems.

**Comment by benwaffle** [comment]
>Nice to see someone still working on a language server implementation

Sorry to say, but our language server has also stalled. I'm still interested in working on it but I don't have time at the moment.

**Comment by jo3d3v** [comment]
There is another implementation on gnome gitlab: https://gitlab.gnome.org/esodan/gvls. Maybe joining your work and skills may produce a working implementation.

**Comment by gavr123456789** [comment]
Any news?

**Comment by jo3d3v** [comment]
The glvs language server is now provided through a ppa: https://launchpad.net/~esodan-gmail/+archive/ubuntu/ppa. But I didn't know any ide which uses them. A PR is proposed for elementary code https://github.com/elementary/code/pull/599. This are my last known news.
